# =====================================================
# DBT Project Configuration
# Project Name: Zoom Gold Dimension Pipeline
# Description: DBT project for transforming Silver data to Gold dimension tables
# Author: Data Engineer
# =====================================================

name: 'zoom_gold_dimension_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_dimension_pipeline'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configs

models:
  zoom_gold_dimension_pipeline:
    # Configuration for all models in this project
    +materialized: table
    +on_schema_change: append_new_columns
    
    # Audit model configuration - runs first
    go_process_audit:
      +materialized: table
      +tags: ["audit", "foundation"]
      +pre_hook: []
      +post_hook: []
    
    # Dimension models configuration
    go_user_dim:
      +materialized: table
      +tags: ["dimension", "scd2", "user"]
    
    go_license_dim:
      +materialized: table
      +tags: ["dimension", "scd2", "license"]

# Variables that can be used throughout the project
vars:
  # Database and schema configurations
  source_database: 'ZOOM_DB'
  source_schema: 'SILVER'
  target_schema: 'GOLD'
  
  # Date configurations
  start_date: '2020-01-01'
  end_date: '2099-12-31'
  
  # SCD configurations
  scd_end_date: '9999-12-31'
  
  # Audit configurations
  audit_enabled: true
  error_handling_enabled: true

# Seeds configuration
seeds:
  zoom_gold_dimension_pipeline:
    +materialized: table

# Snapshots configuration
snapshots:
  zoom_gold_dimension_pipeline:
    +target_schema: 'GOLD_SNAPSHOTS'

# Tests configuration
tests:
  +store_failures: true
  +schema: 'GOLD_TEST_RESULTS'

# Macros configuration
macros:
  zoom_gold_dimension_pipeline:
    +materialized: view

# Documentation configuration
docs:
  generate: true
  
# Dispatch configuration for package compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['zoom_gold_dimension_pipeline', 'dbt_utils']

# Quoting configuration for Snowflake
quoting:
  database: false
  schema: false
  identifier: false

# Require dbt version
require-dbt-version: [">=1.0.0", "<2.0.0"]

# Flags
flags:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  static_parser: true