# DBT Project Configuration for Zoom Gold Dimension Pipeline
# This file configures the DBT project for transforming Silver layer data into Gold dimension tables

name: 'zoom_gold_dimension_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'zoom_gold_dimension_pipeline'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  zoom_gold_dimension_pipeline:
    # Configuration for all models in this project
    +materialized: table
    +on_schema_change: "fail"
    
    # Specific configurations for dimension models
    staging:
      +materialized: view
    
    # Gold layer dimension tables
    gold:
      +materialized: table
      +pre-hook: |
        {% if this.name != 'go_process_audit' %}
          INSERT INTO {{ ref('go_process_audit') }} 
          (execution_id, process_name, pipeline_name, execution_start_time, execution_status, load_date, source_system) 
          SELECT 
            '{{ invocation_id }}', 
            '{{ this.name }}', 
            'gold_dimension_pipeline', 
            CURRENT_TIMESTAMP(), 
            'STARTED', 
            CURRENT_DATE(), 
            'DBT_GOLD_PIPELINE'
        {% endif %}
      +post-hook: |
        {% if this.name != 'go_process_audit' %}
          INSERT INTO {{ ref('go_process_audit') }} 
          (execution_id, process_name, pipeline_name, execution_end_time, execution_status, records_processed, load_date, source_system) 
          SELECT 
            '{{ invocation_id }}', 
            '{{ this.name }}', 
            'gold_dimension_pipeline', 
            CURRENT_TIMESTAMP(), 
            'COMPLETED', 
            (SELECT COUNT(*) FROM {{ this }}), 
            CURRENT_DATE(), 
            'DBT_GOLD_PIPELINE'
        {% endif %}

# Snapshot configurations
snapshots:
  zoom_gold_dimension_pipeline:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Seed configurations
seeds:
  zoom_gold_dimension_pipeline:
    +schema: seeds

# Test configurations
tests:
  zoom_gold_dimension_pipeline:
    +store_failures: true
    +schema: test_failures

# Variables that can be used in models
vars:
  # Source schema configuration
  silver_schema: 'silver'
  gold_schema: 'gold'
  
  # Date variables for incremental processing
  start_date: '2020-01-01'
  end_date: '2099-12-31'
  
  # SCD Type 2 configuration
  scd_end_date: '9999-12-31'
  
  # Audit configuration
  enable_audit_logging: true
  audit_schema: 'gold'
  
  # Data quality configuration
  enable_data_quality_checks: true
  
  # Performance configuration
  batch_size: 10000
  
# Dispatch configuration for cross-database compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_utils']

# Query comment configuration
query-comment:
  comment: 'Generated by DBT for Zoom Gold Dimension Pipeline - {{ node.name }}'
  append: true

# On-run-start and on-run-end hooks
on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS {{ target.schema }}_audit"
  - "CREATE SCHEMA IF NOT EXISTS {{ target.schema }}_test_failures"

on-run-end:
  - "{{ log('DBT run completed for Zoom Gold Dimension Pipeline', info=True) }}"

# Require specific dbt version
require-dbt-version: [">=1.0.0", "<2.0.0"]

# Flags
flags:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  static_parser: true